feat: 두 문자열의 유사도를 측정할 수 있는 calculateSimilarity 함수를 만들고, 문서화를 진행합니다.
toss/es-hangul pull request #104
Opened 2024-05-25 16:47 UTC by okinawaa

fix #49 

## Overview

두 문자열의 유사도를 측정할 수 있는 calculateSimilarity 함수를 만들고, 문서화를 진행합니다.

두 한글 문자열의 유사도를 계산하여 0에서 100 사이의 값을 반환합니다. 이 함수는 es-hangul 라이브러리의 disassembleHangul 메서드를 사용하여 한글 문자열을 자모 단위로 분해하고, [Levenshtein](https://lovit.github.io/nlp/2018/08/28/levenshtein_hangle/) 거리 알고리즘을 이용해 문자열 간의 최소 편집 거리를 계산한 후 이를 바탕으로 유사도를 계산합니다.

## PR Checklist

- [ㅌ] I read and included theses actions below

1. I have read the [Contributing Guide](https://github.com/toss/es-hangul/blob/main/.github/CONTRIBUTING.md)
2. I have written documents and tests, if needed.

2024-05-25 17:07 UTC, okinawaa commented
https://github.com/toss/es-hangul/assets/69495129/41a77a11-5940-4aa4-9a3d-69c1dace95ea

2024-05-26 22:52 UTC, manudeli commented on src/calculateSimilarity.ts
> +  const similarity = ((maxLength - distance) / maxLength) * 100;
```suggestion
  const similarity = ((maxLength - distance) / maxLength);
```

유사도를 표현할 때 퍼센테이지를 표현하고 싶다면 100%가 1이라면 어떨까요? 인터페이스를 사용하는 입장에서 매번 100을 나눠야하는 경우가 많을 거 같아서요

```ts
const result = width * calculateSimilarity(...) / 100 // 이런 패턴이 자주 보일 거 같아요
```

제안코드대로면 / 100이 없을 거 같아요

2024-05-26 23:14 UTC, manudeli commented on src/calculateSimilarity.ts
> +  const disassembledB = disassembleAndClean(b);
XAndY 와 같은 함수명보다는 아래와 같이 사용하는 게 어떨까요?
https://careerly.co.kr/comments/103186

```suggestion
  const disassembledA = disassembleHangul(a).replace(/\s/g, '');
  const disassembledB = disassembleHangul(b).replace(/\s/g, '');
```

2024-05-26 23:21 UTC, manudeli commented on src/calculateSimilarity.ts
> +export function calculateSimilarity(a: string, b: string): number {
사용자는 targetText, inputText라는 parameter명도 볼 수 있기 때문에 좀 더 구체화된 이름이면 좋을 것 같아요

아래는 TypeScript에 정의된 String의 method들이에요
<img width="634" alt="image" src="https://github.com/toss/es-hangul/assets/61593290/8672a095-e953-4402-99a3-46bcbb698452">


```suggestion
export function calculateSimilarity(targetText: string, inputText: string): number {
```

2024-06-01 12:00 UTC, okinawaa commented on src/calculateSimilarity.ts
> +  const similarity = ((maxLength - distance) / maxLength) * 100;
너무 좋은 의견이라고 생각합니다! 
0~100 을 제공하기 보다는 0.00 ~ 1.00 형태로 제공해주도록 수정할게요! 
이유는 말씀해주신 내용 + 다음과 같습니다!

>표준화된 표현: 0.00 ~ 1.00 범위는 많은 라이브러리와 알고리즘에서 유사도를 나타내기 위해 사용하는 표준화된 표현입니다.
정밀도: 소수점을 포함한 범위는 미세한 차이를 더 명확하게 나타낼 수 있습니다.
범용성: 0.00 ~ 1.00 사이의 값은 확률, 비율 등의 다른 측정과 쉽게 통합될 수 있습니다.

2024-06-01 12:07 UTC, okinawaa commented on src/calculateSimilarity.ts
> +  const similarity = ((maxLength - distance) / maxLength) * 100;
[유사도를 0 ~ 100 이 아닌, 0 ~ 1 수로 나타내기:](https://github.com/toss/es-hangul/pull/104/commits/2b2166e0d69dc821df0c8fa6e532ec234d0f56f0)

2024-06-01 12:14 UTC, okinawaa commented on src/calculateSimilarity.ts
> +export function calculateSimilarity(a: string, b: string): number {
이 함수의 목적에 맞게 인자의 이름을 정하는것은 너무 좋은 것 같아요!
하지만, 이 함수의 인자는 단순히 두 문자열이라서 인자의 이름을 정하기가 어려웠는데요, `calculateSimilarity`라는 함수 이름만으로도 두개의 인자가 비교대상이 되는 인자라는 것을 알아차릴 수 있다고 생각했어요. 

제안해주신 코드인 targetText, inputText 를 고려해봤을때, 제 생각은 다음과 같습니다!
1. 사용자는 targetText를 두번째 인자로 넣어도 함수의 결과값은 똑같고
2. 사용자의 input이 아닌, 이미 존재하는 두 값을 비교하려고 해도 이 함수를 사용할 수 있는데 input이라는 맥락으로 좁혀져도 괜찮은가?

**파라미터에 넣어주는 값의 순서가 바뀌어도 값은 동일하고, 함수명의로 인자의 역할이 충분히 설명 가능하다고 생각합니다**

더 떠오르는 구체적인 인자는 요런게 있을 것 같네용

```tsx
export function calculateSimilarity(comparison1: string, comparison2: string): number {
```

2024-06-01 12:38 UTC, manudeli commented on docs/src/pages/docs/api/calculateSimilarity.en.mdx
> +calculateSimilarity('대한민국', '대한밍굮'); // 약0.818
```suggestion
calculateSimilarity('대한민국', '대한밍굮'); // 약 0.818
```

2024-06-01 12:38 UTC, manudeli commented on docs/src/pages/docs/api/calculateSimilarity.ko.mdx
> +calculateSimilarity('동해물과', '동해붇ㄹㅁ과'); // 약0.769
```suggestion
calculateSimilarity('동해물과', '동해붇ㄹㅁ과'); // 약 0.769
```

2024-06-01 12:39 UTC, manudeli commented on docs/src/pages/docs/api/calculateSimilarity.en.mdx
> +calculateSimilarity('가나다라마바사', '나다라마바사가'); // 약0.714
```suggestion
calculateSimilarity('가나다라마바사', '나다라마바사가'); // 약 0.714
```

2024-06-01 12:46 UTC, manudeli commented on src/calculateSimilarity.ts
> +export function calculateSimilarity(a: string, b: string): number {
보통은 1, 2와 같은 숫자를 넣지는 않아서 target, input과 같은 이름을 붙여주었는데 저도 고민되더라구요. 넵넵 일단 이 부분은 다음 버전에서 고려되어도 좋을 것 같기도 해요. 일단 배포하고 이슈따고 고민해봐도 좋을 것 같습니다

2024-06-01 12:49 UTC, manudeli commented on src/calculateSimilarity.ts
> +export function calculateSimilarity(a: string, b: string): number {
이름이 더 심플하면 좋을 것 같아요. calculate가 없어도 좋을 것 같더라구요. date-fns가 add, format과 같은 이름으로 단순하게 제공하는 것 처럼요

```suggestion
export function similarity(a: string, b: string): number {
```

2024-06-01 13:08 UTC, okinawaa commented on src/calculateSimilarity.ts
> +export function calculateSimilarity(a: string, b: string): number {
오오 이거 넘 좋은 관점이네요,
한번 고민 후 다시 코맨트 남기겠습니다!

2024-06-01 13:09 UTC, okinawaa commented on src/calculateSimilarity.ts
> +export function calculateSimilarity(a: string, b: string): number {
처음 제공할때 이름을 확실히 정하고 나가는게 좋을 것 같아서 깊게 고민해보죠!!

2024-06-05 13:21 UTC, evan-moon commented on src/calculateSimilarity.ts
> +export function calculateSimilarity(a: string, b: string): number {
저는 계산한다는 맥락이 굳이 외부에 노출될 필요가 있는 맥락인가하는 생각이 있어서, `getSimilarity`라는 이름도 충분하다고 생각합니다.

@manudeli 님께서 제안주신 `similarity`는 명사라, `const similarity = 유사도함수()`와 같은 use case에서 함수의 결과가 담길 변수와 이름이 충돌할 수 있다는 생각도 들어요!

2024-06-05 13:38 UTC, evan-moon commented on src/calculateSimilarity.ts
> +  const similarity = ((maxLength - distance) / maxLength) * 100;
해당 코멘트 반영된 것 확인하여 Resolve 하겠습니다!
cc. @manudeli

2024-06-05 13:39 UTC, evan-moon commented on src/calculateSimilarity.ts
> +export function calculateSimilarity(a: string, b: string): number {
이 함수를 일종의 이항연산자라고 생각하면 `left`, `right`라는 이름도 괜찮을 것 같은데 어떠신가요???

2024-06-08 01:36 UTC, okinawaa commented on src/calculateSimilarity.ts
> +export function calculateSimilarity(a: string, b: string): number {
**getSimilarity** 좋습니다! 간결하고 오해의 소지가 없을 것 같아요

2024-06-08 01:44 UTC, okinawaa commented on src/calculateSimilarity.ts
> +export function calculateSimilarity(a: string, b: string): number {
left, right좋네요!

2024-06-08 06:30 UTC, manudeli commented on src/calculateSimilarity.ts
> +export function calculateSimilarity(a: string, b: string): number {
@okinawaa @evan-moon 함수들 명명 규칙을 정해보면 좋겠어요. BREAKING CHANGE가 있기는 하겠지만 아직 사용량이 적을 때 명명규칙을 정하고 빠르게 BREAKING CHANGE를 내는 것도 장기적으로 도움이 될 수 있을 거 같아요

disassembleHangul, disassembleHangulToGroup도 disassemble로는 어떨까요? (BREAKING CHANGE 필요) Hangul이라는 맥락을 알필요가 있었다면 getSimilarityHangul이어야 하는지 아닌지 정의할 필요가 있을 거 같아요
```ts
disassemble(korStr, { type: 'string' }) // disassembleHangul
disassemble(korStr, { type: 'array' }) // disassembleHangulToGroup
```

2024-06-11 09:17 UTC, evan-moon commented on src/calculateSimilarity.ts
> +export function calculateSimilarity(a: string, b: string): number {
좋은 제안인 것 같습니다.
저는 가급적이면 Hangul이라는 맥락이 함수명에 포함되는 것이 좋다고 생각하는데요.

물론 `import { disassemble } from 'es-hangul'`과 같은 구문을 보면 "이 함수가 한글을 분해한다"라는 맥락을 파악할 수는 있겠으나, import 문의 특성 상 모듈의 최상단에 위치하여 함수가 소비되는 곳과의 거리가 멀 가능성이 높다는 점이 그 이유인데요.

이런 상황이라면 개발자가 `disassemble`이라는 추상 레벨이 높은 함수명만 보고 함수의 역할과 동작을 예측하기 어렵기 때문에 좋은 네이밍이 아니라고 생각했어요.

그래서 함수명만으로도 명확하게 함수의 역할과 동작을 예측할 수 있는 `*Hangul`이라는 네이밍이 더 DX에 좋지 않을까 했습니다.

2024-06-12 04:31 UTC, manudeli commented on src/calculateSimilarity.ts
> +export function calculateSimilarity(a: string, b: string): number {
> 물론 import { disassemble } from 'es-hangul'과 같은 구문을 보면 "이 함수가 한글을 분해한다"라는 맥락을 파악할 수는 있겠으나, import 문의 특성 상 모듈의 최상단에 위치하여 함수가 소비되는 곳과의 거리가 멀 가능성이 높다는 점이 그 이유인데요.

저도 이 점에 동의해요. 그리고 이에 더해서 date-fns와는 es-hangul이 인자를 받는 데에 다른 특징을 갖고 있다고 생각했어요. date-fns의 add, format는 date라는 맥락이 함수명에 포함되지 않아도 괜찮은 게 인자로 받는 변수명에 그 내용이 포함될 가능성이 높아서라고 생각했어요.

```ts
add(createdAt, { day: 1 }) // 변수명 createdAt에서 Date객체임을 알 수 있음
add('hello', { day: 1 }) // 타입에러! Date객체여야 함
```

es-hangul의 경우 변수명이나 타입적으로 인자가 변수라는 것을 알 수 없기 때문에 Hangul이라는 맥락이 disassembleHangul에 포함되는 것이 더 좋다고 생각했어요

### Bad

```ts
disassemble(user.name) // user.name이 한국어야 한다는 것을 알 수 없음
disassemble('English Name') // 한국어가 아니더라도 타입에러가 발생하지 않음
```

### Good

```ts
disassembleHangul(user.name) // 한국어야 한다는 것을 알 수 없음. 하지만 hangul인지 검사 필요하다는 것을 이해할 수 있음
disassembleHangul('English Name') // 한국어가 아니더라도 타입에러가 발생하지 않음 하지만 이상함을 이해할 수 있음
```

그래서 String이지만 한글이어야하는 인자를 받는 경우에 함수명에 `~~~Hangul`과 같은 suffix가 있으면 하는 바람이 있습니다

2024-06-13 09:52 UTC, evan-moon approved these changes
LGTM입니다

2024-06-13 11:21 UTC, manudeli requested changes

2024-06-13 11:21 UTC, manudeli commented on docs/src/pages/docs/api/getSimilarity.en.mdx
> +```
```suggestion
```tsx
function getSimilarity(
  // First Korean string to compare
  left: string,
  // Second Korean string to compare
  right: string
): number;
```
```

2024-06-13 11:21 UTC, manudeli commented on src/isOnlyChosung.ts
> +}
필수는 아니지만 이 함수는 외부로 노출하는 것이 아니라면 utils폴더에 정리하고 src에는 외부로 노출하는 함수만을 두면 더 좋을 거 같아요. 많은 라이브러리들의 폴더 구조에서 이런 형태를 기대해서 구분하면 더 좋을 거 같아요

2024-06-13 11:23 UTC, manudeli commented
커밋메시지에도 getSimilarity로 나오도록 PR title와 description에도 calculateSimilarity -> getSimilarity를 반영하면 더 좋을 거 같아요

2024-06-14 12:41 UTC, manudeli commented on src/calculateSimilarity.ts
> +export function calculateSimilarity(a: string, b: string): number {
이슈화 해두었습니다 https://github.com/toss/es-hangul/issues/121

2024-06-18 15:57 UTC, okinawaa commented on src/isOnlyChosung.ts
> +}
좋습니다!
이 파일이 왜 이 PR에 끼어들어갔는지 의문이네요.. 파일 자체를 우선 제거할게요

2024-06-18 21:29 UTC, manudeli commented
changeset 추가가 필요해요

2024-06-18 21:32 UTC, manudeli commented on src/getSimilarity.ts
> +export function getSimilarity(left: string, right: string): number {
https://github.com/toss/es-hangul/pull/104#discussion_r1635798951

여기 내용대로면 getSimilarity, getSimilarityHangul, similarityHangul 중에 하나로 결정이 필요해요. 이 부분은 네이밍 규칙이 없이는 BREAKING CHANGE가 클 가능성이 높기 때문에 정리하고 배포되면 좋겠습니다

2024-06-22 14:19 UTC, okinawaa commented on src/getSimilarity.ts
> +export function getSimilarity(left: string, right: string): number {
`getHangulSimilarity` 라는 함수명은 어떤가요?

함수가 짧은것보다는, 맥락을 드러내는 적절한 이름이라고 생각합니다. `getTwoHangulSimilarity`와 같은 이름도 생각해봤지만, 인자를 두 개 받기때문에 충분히 알 수 있고, 유사성이라는것은 두개를 비교한다는것은 충분히 알 수 있다고 생각해요

2024-06-22 14:53 UTC, okinawaa commented on src/getSimilarity.ts
> +export function getSimilarity(left: string, right: string): number {
위처럼 생각했지만, `getSimilarity`라고 명명하는것도 좋을 것 같아서 코맨트 남겨봤어요.

https://github.com/toss/es-hangul/issues/121#issuecomment-2184060417

2024-06-24 17:12 UTC, manudeli commented on src/getSimilarity.ts
> +export function getSimilarity(left: string, right: string): number {
https://github.com/toss/es-hangul/issues/121 에서 일관된 이름짓기 논의를 마치고 이슈를 닫은 후 규칙대로 변경된 기능들만 머지되면 좋겠습니다

2024-07-02 14:13 UTC, okinawaa commented
@manudeli 님 이 PR의 거의 모든 부분에 기여해주셨기때문에, coauthors를 이용하여 공동작업자로 추가했어요!!

2024-07-02 21:19 UTC, manudeli commented
> @manudeli 님 이 PR의 거의 모든 부분에 기여해주셨기때문에, coauthors를 이용하여 공동작업자로 추가했어요!!

감사해요! 👍

2024-07-03 08:06 UTC, minsoo-web commented on docs/src/pages/docs/api/getSimilarity.ko.mdx
> +): number;
엄청 중요하진 않은 것 같은데, 문서에서는 left, right 라는 표현을 썼는데 주석에는 첫 번째 / 두 번째 라고 쓰이고 테스트 코드에서는 target, input 이라는 표현이 쓰이고 있어요. 통일된 표현을 사용하면 어떨까요? 🤔

2024-07-03 08:06 UTC, minsoo-web commented on docs/src/pages/docs/api/getSimilarity.ko.mdx
> +두 한글 문자열의 유사도를 계산하여 0에서 1 사이의 값을 반환합니다. 이 함수는 es-hangul 라이브러리의 disassemble 메서드를 사용하여 한글 문자열을 자모 단위로 분해하고, Levenshtein 거리 알고리즘을 이용해 문자열 간의 최소 편집 거리를 계산한 후 이를 바탕으로 유사도를 계산합니다.
한글이라기보다는 두 문자열에 대한 유사도 측정인데, 문서에서 한글이라고 표현하는 것이 좋을까요?
혹은 영문이 섞이면, 의 엣지 케이스 등을 테스트 코드에서 대응해야 할까요?

2024-07-04 14:44 UTC, okinawaa commented on docs/src/pages/docs/api/getSimilarity.ko.mdx
> +두 한글 문자열의 유사도를 계산하여 0에서 1 사이의 값을 반환합니다. 이 함수는 es-hangul 라이브러리의 disassemble 메서드를 사용하여 한글 문자열을 자모 단위로 분해하고, Levenshtein 거리 알고리즘을 이용해 문자열 간의 최소 편집 거리를 계산한 후 이를 바탕으로 유사도를 계산합니다.
음.. 이 부분 너무 잘 말씀해주신 것 같네요..
몇 가지 방법이 생각나는데 어느 방안이 가장 베스트일지 고민입니다!!  ㅠㅠ


1. 한글 이외의 값이 left, right에 들어있으면 에러를 던진다.
2. 한글 이외의 값이 left, right에 들어있으면 무조건 0을 리턴한다. 
3. 한글 이외의 값이 left, right에 들어있으면 한글 제외 문자를 제거하고 값을 계산한다.

2024-07-05 05:26 UTC, okinawaa commented on docs/src/pages/docs/api/getSimilarity.ko.mdx
> +두 한글 문자열의 유사도를 계산하여 0에서 1 사이의 값을 반환합니다. 이 함수는 es-hangul 라이브러리의 disassemble 메서드를 사용하여 한글 문자열을 자모 단위로 분해하고, Levenshtein 거리 알고리즘을 이용해 문자열 간의 최소 편집 거리를 계산한 후 이를 바탕으로 유사도를 계산합니다.
내부에서 복잡한 처리를 하기 보다는, 
특수문자와, 영어, 숫자를 받을 수 있도록 처리해줬습니다!

1. 문서에 한글 문자열이라는 사항을 문자열 로 변경했습니다.
2. 적절한 테스트코드를 작성해줬습니다!

좋은 코맨트 감사합니다!

2024-07-09 04:32 UTC, okinawaa commented
너무나 많은 분들이 도움을 주셨지만, 
es-hangul의 [방향성 문제](https://github.com/toss/es-hangul/discussions/176)로  이 PR은 닫을게요.

이 메서드의 코어한 로직은, 한글의 복잡도를 이해한 뒤, 유사도를 계산한다기 보다는 [Levenshtein](https://lovit.github.io/nlp/2018/08/28/levenshtein_hangle/) 을 사용하는것에 불과하다고 생각합니다.

이 기능을 구현하고 싶다면, disassembleHangul 함수와 levenshetein 알고리즘을 이용해서 직접 구현할 수 있을거라고 생각합니다.
물론 더 좋은 알고리즘이 있다면 그것을 이용해도 좋고요!

2024-07-09 04:32 UTC, closed without merging