feat: 한국어를 로마자로 변환해주는 함수와 한국어를 표준 발음법으로 변환해주는 함수를 만들고 문서화를 진행합니다
toss/es-hangul pull request #115
Opened 2024-06-04 18:53 UTC by po4tion

feat #33 

## Overview

한글을 로마자로 변경하기 위해서는 다음과 같은 프로세스가 필요합니다.
1. 입력받은 한글을 표준 발음법으로 변경합니다.
2. 표준 발음법으로 변경된 한글을 로마자로 변경합니다. 단, 로마자 표기법은 된소리되기를 반영하지 않으므로 경음화가 적용되지 않은 표준 발음법을 기준으로 적용합니다.

[한국어 어문 규범의 표준 발음법](https://korean.go.kr/kornorms/regltn/regltnView.do?regltn_code=0002#a346)을 지키며 한글을 표준 발음법으로 변환하는 standardPronunciation 함수를 만들고 문서화를 진행하였습니다. standardPronunciation 함수는 표준어 규정(문화체육관광부 고시 제2017-13호)의 제2부 표준발음법의 4장(받침의 발음), 5장(음의 동화), 6장(경음화)를 기반으로 기능을 구현하였습니다.

standardPronunciation 함수로 반환받은 표준 발음법(단, 경음화 제거)을 로마자로 변경합니다. [한국어 어문 규범의 '국어의 로마자 표기법'](https://korean.go.kr/kornorms/regltn/regltnView.do?regltn_code=0004&regltn_no=444#a444)을 참고하여 romanize 함수를 만들고 문서화를 진행하였습니다.

참고하실 수 있는 자료
1. https://korean.go.kr/kornorms/main/main.do
2. https://www.hankookilbo.com/News/Read/201611221071387854
3. https://www.korean.go.kr/front/page/pageView.do?page_id=P000149&mn_id=99
4. https://www.youtube.com/watch?v=gKRKVVLaDsM
5. https://www.youtube.com/watch?v=UVStu0RVlCE
6. https://www.youtube.com/watch?v=Mm2JX2naqWk
7. http://contents2.kocw.or.kr/KOCW/data/document/2020/seowon/choiyungon0805/12.pdf
8. https://www.youtube.com/watch?v=mubHE707Eo4

## PR Checklist

- [X] I read and included theses actions below

1. I have read the [Contributing Guide](https://github.com/toss/es-hangul/blob/main/.github/CONTRIBUTING.md)
3. I have written documents and tests, if needed.

2024-06-08 03:44 UTC, okinawaa commented on docs/src/pages/docs/api/romanize.en.md
> +romanize('안녕하세요, 토스입니다.'); // 'annyeonghaseyo, toseuimnida.'
특정 회사명이 나오는것은 지양하는것이 어떨까요!?
라이브러리 특성상 문서에서 특정 회사에 대한 언급은 없었으면 해요!

2024-06-08 03:44 UTC, okinawaa commented on src/utils.ts
> +export function isIncludedInArray<T>(array: readonly T[], value: unknown): value is T {
보다 간결하게, arrayIncludes라는 함수명은 어떤가요?

https://www.slash.page/libraries/common/utils/src/array/arrayincludes.i18n/

2024-06-08 04:53 UTC, okinawaa commented on src/standardPronunciation.ts
> +export function standardPronunciation(
함수이기 때문에, 명사가 아닌 동사를 사용하는것은 어떤가요~?

<img width="1331" alt="image" src="https://github.com/toss/es-hangul/assets/69495129/4ac594bc-9688-4d26-8ddb-9a0c535cb7c1">
```suggestion
export function standardizePronunciation(
```

2024-06-08 04:58 UTC, okinawaa commented on src/constants.ts
> +export const 특별한_한글_자모 = ['디귿', '지읒', '치읓', '키읔', '티읕', '피읖', '히읗'] as const;
특별하다는 것은 어떠한 기준에서 나온것인지 궁금합니당!

요번 #115 에서 constants.ts에 선언된 상수들은, 주로 `standartPronuciation` 에 사용되기 위함으로 보이는데요, 추후 다른 함수에서도 사용될 수도 있지만, 현재는 상수명이나 주석을 보면 `standartPronuciation` 에 강결합되어있는것 같아요.

`constants.ts`라는 제네럴한 파일에, `standartPronuciation` 에 강결합된 상수들이 선언되있다고 생각하는데요.

두 가지 방법으로 풀어보면 어떨까요?

1. constants.ts 파일에 지금처럼 선언하되, `standartPronuciation` 맥락을 제거한다.
2. `standartPronuciation.constants.ts` 파일을 생성한 뒤, 거기에 `standartPronuciation` 에 사용될 상수를 선언한다.

2024-06-08 05:14 UTC, okinawaa commented on src/standardPronunciation.ts
> +    .map(syllable => disassembleCompleteHangulCharacter(syllable))
매우 사소하지만, 309번째 줄에 filter구문과 형태를 맞춰줘도 좋을 것 같아요!

```suggestion
    .map(disassembleCompleteHangulCharacter)
```

2024-06-24 17:11 UTC, manudeli commented
@po4tion https://github.com/toss/es-hangul/issues/121 일관된 이름짓기 규칙이 만들어지고 이 기능이 추가되는 것이 맞다고 생각해서 남깁니다

2024-06-26 01:18 UTC, po4tion commented on src/constants.ts
> +export const 특별한_한글_자모 = ['디귿', '지읒', '치읓', '키읔', '티읕', '피읖', '히읗'] as const;
> 특별하다는 것은 어떠한 기준에서 나온것인지 궁금합니당!

![image](https://github.com/toss/es-hangul/assets/55759551/765421ec-7f84-42fd-9610-5eab70c9ff88)
한국어 어문 규범 제4장 16항을 보면 다른 자모들과 다르게 "ㄷ, ㅈ, ㅊ, ㅋ, ㅌ, ㅍ, ㅎ"만 특별하게 발음해야 하기 때문에 "특별한" 이라는 PREFIX를 붙였습니다.

> 두 가지 방법으로 풀어보면 어떨까요?

새로운 상수 파일을 생성한 뒤에 선언할게요. 표준발음법 함수의 맥락을 제거하면 코드를 이해하는 복잡도가 증가할 것 같아요.

2024-06-26 01:22 UTC, po4tion commented on docs/src/pages/docs/api/romanize.en.md
> +romanize('안녕하세요, 토스입니다.'); // 'annyeonghaseyo, toseuimnida.'
좋은 의견이네요. 동의해요.
[fix: 특정회사 언급 문자 제거](https://github.com/toss/es-hangul/pull/115/commits/1bc3dd29e244bf5fe6cec5f781a8c7ba93db8b66)

2024-06-26 01:33 UTC, po4tion commented on src/utils.ts
> +export function isIncludedInArray<T>(array: readonly T[], value: unknown): value is T {
slash의 code를 참고하여 수정하였어요.
[fix: arrayIncludes 함수를 개선합니다](https://github.com/toss/es-hangul/pull/115/commits/c7b3964eef108afd020bef3044c9ceb917c3e3da)

2024-06-26 01:34 UTC, po4tion commented on src/standardPronunciation.ts
> +export function standardPronunciation(
https://github.com/toss/es-hangul/pull/132#discussion_r1652126733

위의 논의가 끝나고 함수 명명규칙이 더 확고해지면 그때 함수 이름을 변경할게요. 해당 리뷰는 잠시 보류해놓을게요.

2024-06-26 01:35 UTC, po4tion commented on src/standardPronunciation.ts
> +    .map(syllable => disassembleCompleteHangulCharacter(syllable))
꼼꼼히 봐주셔서 감사해요!
[fix: map 메소드를 축약한다](https://github.com/toss/es-hangul/pull/115/commits/32218655106a116ad2aa94809fffa2600ba3d0e8)

2024-06-26 02:18 UTC, po4tion commented on src/romanize.ts
> +export function romanize(hangul: string): string {
#121 이슈에 따라서 romanizeHangul로 이름을 변경하였습니다.

2024-06-29 13:32 UTC, okinawaa commented on src/romanizeHangul.spec.ts
> +describe('romanizeHangul', () => {
한글, 특수문자 이외 영어가 섞인 파라미터가 들어오면 어떻게 되나요?

2024-06-29 14:19 UTC, po4tion commented on src/romanizeHangul.spec.ts
> +describe('romanizeHangul', () => {
@okinawaa 님 예리한 질문 감사드립니다. 답변드리자면 영어는 그대로 반환해주는데요. 예를 들어, "고양이는cat" 문자열은 "goyangnineuncat"으로 변경됩니다.
관련하여 테스트 케이스 추가하였습니다.
[test: 한글과 영어가 혼합된 테스트 케이스를 추가합니다](https://github.com/toss/es-hangul/pull/115/commits/e08251ca4dee8804b33a63cbbbd78ba64870b7e2)

2024-07-01 15:10 UTC, po4tion commented on src/standardPronunciation/standardPronunciation.rules.ts
> +    // ㄴ/ㄹ이 되기 위한 조건이지만 현재 음절의 중성의 가로획이 하나가 아닐 경우에는 덧나지 않고 연음규칙이 적용된다
"고양이" 단어를 테스트 해보다가 "고양니"라고 변환되는 것을 발견했는데요. ㄴ/ㄹ이 덧날 조건에 부가 조건이 붙는다는 것을 발견하여 추가하였습니다.
이 부가 조건은 따로 한국어 어문 규범에 나오지는 않고, "[한글 연구소](https://cafe.daum.net/v1732)"를 운영하시는 장덕진 선생님께서 도움주셨습니다.

2024-07-01 15:20 UTC, po4tion commented on src/standardPronunciation/standardPronunciation.rules.ts
> +    // ㄴ/ㄹ이 되기 위한 조건이지만 현재 음절의 중성의 ∙(아래아)가 하나가 아닐 경우에는 덧나지 않고 연음규칙이 적용된다
"고양이" 단어를 테스트 해보다가 "고양니"라고 변환되는 것을 발견했는데요. ㄴ/ㄹ이 덧날 조건에 부가 조건이 붙는다는 것을 발견하여 추가하였습니다.
이 부가 조건은 따로 한국어 어문 규범에 나오지는 않고, "[한글 연구소](https://cafe.daum.net/v1732)"를 운영하시는 장덕진 선생님께서 도움주셨습니다.

주석에 보이는 **아래아**라는 용어는 [한국민족문화대백과사전](https://encykorea.aks.ac.kr/Article/E0074518)에서 확인할 수 있습니다.
![image](https://github.com/toss/es-hangul/assets/55759551/7a7ac54a-5568-451d-a082-0370aa0ec66b)

2024-07-03 06:07 UTC, okinawaa commented on src/standardizePronunciation/standardizePronunciation.rules.ts
> +    currentSyllable.last = currentSyllable.last === 'ㄹㅌ' ? 'ㄹ' : '';
이 부분을 포함하여, apply* 함수들이 파라미터로 받은 값을 변화시키고 있는 것 같아요.
함수를 선언할때, 파라미터의 불변성을 유지하는것이 중요하다고 생각하는데요.

```
1. 예상치 못한 부작용 발생

함수 내부에서 파라미터를 변형하게 되면, 함수 외부에서 해당 파라미터 어떻게 변할지 예측하기 어려워집니다. 사이드 이펙트 가능성이 있습니다.

2. 순수 함수의 원칙 위반

순수 함수는 동일한 입력에 대해 항상 동일한 출력을 반환하며, 외부 상태나 인자를 변경하지 않습니다. 인자를 변형하면 순수 함수의 원칙을 위반하게 되며, 이는 코드의 가독성 및 유지보수성을 저하시킵니다. 순수 함수는 테스트와 리팩토링이 용이하다는 장점이 있습니다.

3. 코드 재사용성 저하

인자를 변형하지 않는 함수는 보다 재사용성이 높습니다. 여러 곳에서 동일한 함수를 호출하더라도, 인자가 변형되지 않기 때문에 안심하고 사용할 수 있습니다. 반면, 인자를 변형하는 함수는 다른 곳에서 사용하기 어렵고, 재사용성을 떨어뜨립니다.
```

실제 파라미터를 변경하지 않고 다음과 같은 인터페이스로 고려해볼수 있을까요? 룰이 적용된 값을 반환해주도록요!

```
const appliedSyllable = apply*(currentSyllable);
```

2024-07-03 06:07 UTC, okinawaa commented on src/standardizePronunciation/index.ts
> +  return changedHangul.join(' ');
이 코드의 개선점이 2가지 생각나는데요, 

1. 전역 변수에 값이 반복문을 돌면서 계속 바뀐다,
2. 명령형 흐름으로 코드가 작성되어있어서, 인지적 부담이 있다.

전역 변수를 사용하지 않고, SRP원칙에 따라서 함수를 적절한 기준으로 쪼개보면 다음과 같이 사용할 수 있을 것 같아요. 

```suggestion
  const processSyllables = (syllables: string[], phrase: string, options: any) =>
    syllables.map((currentSyllable, I, array) => {
      const nextSyllable = I < array.length - 1 ? array[I + 1] : null;
      applyRules(currentSyllable, nextSyllable, I, phrase, options);
      return currentSyllable;
    });

  const transformHangulPhrase = (phrase: string, options: any): string => {
    const { notHangulPhrase, disassembleHangul } = 음절분해(phrase);
    const processedSyllables = processSyllables(disassembleHangul, phrase, options);
    return assembleChangedHangul(processedSyllables, notHangulPhrase);
  };

  return hangul
    .split(' ')
    .map(phrase => transformHangulPhrase(phrase, options))
    .join(' ');

```

2024-07-03 06:07 UTC, okinawaa commented on src/standardizePronunciation/index.ts
> +  return changedHangul.join(' ');
apply 쪽 코드들도, 대부분 명령형으로 코드가 구현되어있어서 코드를 읽는데에 시간이 많이 드는것 같아요.
위에서부터 아래로 순차적으로 눈을 내려가며 읽을걸 고려한다면, 조금 더 다른방향으로 리팩토링했으면 좋겠어요

2024-07-07 16:32 UTC, po4tion commented on src/standardizePronunciation/index.ts
> +  return changedHangul.join(' ');
@okinawaa 위에서 언급하셨던 RORO 패턴과 순수함수 원칙을 적용했어요. 그리고 말씀주신 것처럼 apply 코드는 읽기에 쉽지 않다고 생각해서 각 규칙을 분리하여 선언형으로 작성하고 테스트 케이스를 추가했습니다.

2024-07-21 14:11 UTC, okinawaa requested changes

2024-07-21 14:11 UTC, okinawaa commented on src/romanize.spec.ts
> +describe('romanize', () => {
테스트 케이스 it으로 나눠주신것 감탄했습니다..!! 너무 좋네요 👍

2024-07-21 14:11 UTC, okinawaa commented on src/utils.ts
> +export function arrayIncludes<Type>(array: Type[] | readonly Type[], item: unknown, fromIndex?: number): item is Type {
요 함수들, 혹시 _internal/index.ts 에 구현해주실 수 있나요?
utils.ts파일은 점진적으로 제거해나가고자 합니다!

#158

2024-07-22 03:29 UTC, okinawaa commented
conflic도 해결 부탁드립니당! 🙏

2024-07-27 16:33 UTC, po4tion commented on src/utils.ts
> +export function arrayIncludes<Type>(array: Type[] | readonly Type[], item: unknown, fromIndex?: number): item is Type {
[fix: isNotUndefined, defined, arrayIncludes를 internal로 이동합니다.](https://github.com/toss/es-hangul/pull/115/commits/a298eb59b8cdeef4aaf3b380458e41e2a6208457) `_internal/index.ts`로 이동시켰습니다.

2024-07-27 16:34 UTC, po4tion commented
@okinawaa conflict 해결하였습니다.

2024-08-04 08:34 UTC, po4tion commented
conflict 해결하였습니다.

2024-08-04 10:40 UTC, okinawaa approved these changes
너무 값진 작업 감사합니다 🙇

2024-08-04 10:40 UTC, merged