feat: 문자열에서 한글만 반환하는 parseHangul을 구현합니다.
toss/es-hangul pull request #130
Opened 2024-06-23 16:56 UTC by Collection50

## Overview

문자열에서 한글만 반환하는 `parseHangul`을 구현합니다.

```ts
parseHangul('안녕하세요1234abc'); // '안녕하세요'
parseHangul('abcde'); // ''
parseHangul('안녕하세요ㄱㄴ'); // '안녕하세요ㄱㄴ'
parseHangul('안녕하세요    만나서 반갑습니다'); // '안녕하세요    만나서 반갑습니다'
parseHangul('가나다!-29~라마바.,,사'); // '가나다라마바사'
```

## 고민점

- `\s` 정규표현식을 통해 `\n`과 같은 `escape` 문자열은 한글로 인식되어 처리하고 있습니다.
- `escape` 문자열도 필터링할 지에 대해 고민 후, 한글과 혼용되어 사용될 것이라 생각하고 필터링하지 않았습니다.

## PR Checklist

- [x] I read and included theses actions below

1. I have read the [Contributing Guide](https://github.com/toss/es-hangul/blob/main/.github/CONTRIBUTING.md)
2. I have written documents and tests, if needed.

2024-06-24 11:57 UTC, manudeli commented on src/parseHangul.ts
> +export function parseHangul(str: string): string {
@okinawaa https://github.com/toss/es-hangul/issues/121 이름짓기 이슈가 해결되고 머지되면 좋겠습니다

2024-06-24 13:07 UTC, Collection50 commented on src/parseHangul.ts
> +export function parseHangul(str: string): string {
@manudeli  #121 이슈에 의견이 필요하다는 말씀일까요??

2024-06-24 16:48 UTC, crucifyer commented
이 함수 명칭은 removeUnHangul 같은 지운다는 뜻을 포함했으면 좋겠습니다.

정규식에서 + 는 큰 단위의 반복을 줄여 성능을 높이는 효과가 있습니다.
bench: https://jsfiddle.net/crucify/g74b5d1h/

ps. 저 식대로면 ㅠㅠ 같은 문자도 지워지는데 함수의 역할이 무엇인가요?

2024-06-24 16:54 UTC, okinawaa commented
>이 함수 명칭은 removeUnHangul 같은 지운다는 뜻을 포함했으면 좋겠습니다.

이 부분에 동의하여, 한글을 지운다는 맥락을 설명할 수 있는 함수명, 혹은 주석에 "한글을 추출" 한다고 작성해주신것을 따라 `extractHangul` 정도는 어떨까요? 현재 parseHangul이 약간 함수의 동작을 정확히 설명하기에 모호하다고 생각이 들어서요. !

2024-06-24 16:56 UTC, okinawaa commented
>escape 문자열도 필터링할 지에 대해 고민 후, 한글과 혼용되어 사용될 것이라 생각하고 필터링하지 않았습니다.

이 부분은 현재 구현대로 띄어쓰기는 삭제하지 않는 것이 좋을 것 같아요~ 라이브러리를 사용하는쪽에서 정말 띄어쓰기를 삭제하고 싶으면 사용하는 쪽에서 제어할 것 이라고 생각해요

2024-06-25 01:09 UTC, Collection50 commented
@crucifyer 피드백 해주셔서 감사합니다 !

2024-06-25 01:10 UTC, Collection50 commented
@okinawaa 
> 이 부분에 동의하여, 한글을 지운다는 맥락을 설명할 수 있는 함수명, 혹은 주석에 "한글을 추출" 한다고 작성해주신것을 따라 extractHangul 정도는 어떨까요? 현재 parseHangul이 약간 함수의 동작을 정확히 설명하기에 모호하다고 생각이 들어서요. !

테스트 코드 보완과 함께 수정 완료 했습니다 !

2024-06-29 11:42 UTC, okinawaa commented on src/extractHangul.spec.ts
> +describe('extractHangul 함수 테스트', () => {
일관성을 유지하기 위해서 , 함수 테스트 글자를 지우는것은 어떨까요?

```suggestion
describe('extractHangul', () => {
```

2024-06-29 11:42 UTC, okinawaa commented on src/extractHangul.spec.ts
> +
추후 다른 PR에서 작업되도 좋겠습니다,
현재 it구문이 너무 병렬적으로 나와있으니 인지적으로 힘든 것 같아요.
비슷한 맥락인 것들은 describe 메서드를 사용해 한번 grouping해주면 좋을 것 같아요

2024-06-29 13:00 UTC, Collection50 commented on src/extractHangul.spec.ts
> +describe('extractHangul 함수 테스트', () => {
넵 !

2024-06-29 13:01 UTC, Collection50 commented on src/extractHangul.spec.ts
> +
넵 추가적인 PR 만들겠습니다 !

2024-06-29 13:44 UTC, okinawaa requested changes
extractHangul에 대한 문서 작업도 진행해주시면 감사하겠습니다.
API가 실제로 추가되는것이기때문에 문서에서도 표현되었으면 좋겠어요!

2024-06-29 13:45 UTC, okinawaa commented on src/extractHangul.spec.ts
> +  it('숫자와 알파벳 추출', () => {
숫자
```suggestion
  it('숫자와 알파벳를 제외한 한글 추출', () => {
```

2024-06-29 13:46 UTC, okinawaa commented on src/extractHangul.spec.ts
> +  });
한글을 추출하여, return값으로 주는것이기때문에
한글을 `추출`하고, 다른건 `제외`한다는 표현을 사용하면 좋을 것 같아요

2024-06-29 14:03 UTC, Collection50 commented
@okinawaa 
중복되는 테스트 코드를 삭제하여 가독성 향상했습니다 !
문서 작성 완료했습니다 !

2024-06-29 14:10 UTC, okinawaa commented on src/extractHangul.ts
> +export function extractHangul(str: string): string {
실제 사용할 수 있도록 src/index.ts에서 export 해주시면 좋을 것 같아요

2024-06-29 14:11 UTC, Collection50 commented on src/extractHangul.ts
> +export function extractHangul(str: string): string {
완료했습니다 ! 감사합니다 !

2024-06-29 14:16 UTC, okinawaa approved these changes
긴 작업 감사합니다!

2024-06-29 14:16 UTC, merged