feat : 문장의 각 단어 중 첫 문자만 뽑는 함수추가 ( #128 이슈에 대한 )
toss/es-hangul pull request #133
Opened 2024-06-25 06:55 UTC by KNU-K

feat : 문장의 각 단어 중 첫 문자만 뽑는 함수추가
> test 및 함수 추가

## Overview

문장 내에서 단어의 첫 문자만 뽑는 함수를 추가하였습니다.

## PR Checklist

- [x] I read and included theses actions below

1. I have read the [Contributing Guide](https://github.com/toss/es-hangul/blob/main/.github/CONTRIBUTING.md)
2. I have written documents and tests, if needed.

2024-06-27 17:44 UTC, po4tion commented on src/getFirstHangulLetters.ts
> +}
매개변수가 한글인지 검증하는 로직이 필요하지 않을까요? 지금은 한글이 아니더라도 반환을 해주는데요. 함수명과 기능이 불일치하는 것 같아요. 그리고 매개변수명은 `str`말고 더 직관적인 이름이 있을 것 같아요!

2024-06-28 17:35 UTC, KNU-K commented on src/getFirstHangulLetters.ts
> +}
넵 정정해보겠습니다.

2024-06-28 18:05 UTC, KNU-K commented
@po4tion 추가했습니다. 확인 부탁드립니다.

2024-06-29 11:50 UTC, okinawaa commented on src/getFirstHangulLetters.ts
> +export function getFirstHangulLetters(text: string) {
메서드가 하는 역할에 비해서, 메서드이름이 약간 일반적(general)이라고 생각했는데요, 
왜냐하면 메서드 이름만 보고 띄어쓰기를 기준으로 나누고, 가장 앞의 글자들을 가져온다는것을 예측하기 힘들 것 같아요. 한번 고민해보겠습니다!

2024-06-29 11:54 UTC, okinawaa commented on src/_internal/hangul.ts
> +export function isHangulText(text: string): boolean {
요렇게 조금 더 명확히 한글만 있는가를 검증하는것을 나타내는것은 어떤가요?

```suggestion
export function isHangulOnly(text: string): boolean {
```

2024-06-29 12:19 UTC, okinawaa commented on src/_internal/hangul.ts
> +export function isHangulText(text: string): boolean {
사용하는쪽도 수정이 되면 좋겠습니다~ 감사합니다 🙇

2024-06-29 12:22 UTC, KNU-K commented on src/getFirstHangulLetters.ts
> +export function getFirstHangulLetters(text: string) {
메서드 이름을 `getHangulAbbreviation()` 나 `getHangulAcronym()`은 어떨까요?

2024-06-29 12:38 UTC, KNU-K commented on src/getFirstHangulLetters.ts
> +export function getFirstHangulLetters(text: string) {
`extractFirstHangulFromWords()`과 `extractFirstHangul()` 도 고려하고 있습니다.

word들에서 첫번째 한글을 추출해서 list 로 return 해주는게 기능이라 해당 이름도 좋을 것 같습니다.

꽤나 유용할 것 같은 기능으로 생각됩니다. @okinawaa

2024-06-29 12:42 UTC, okinawaa commented on src/getFirstHangulLetters.ts
> +export function getFirstHangulLetters(text: string) {
너무 좋은 함수명들이네요, `getHangulAcronym` 이것이 오해의 소지 없이 정확히 함수의 역할을 설명하고 있는것 같아서, 사용하면 좋을 것 같은데 @KNU-K 님께서는 어떠신가요~?

2024-06-29 12:44 UTC, KNU-K commented on src/getFirstHangulLetters.ts
> +export function getFirstHangulLetters(text: string) {
`getHangulAcronym`로 바로 수정하겠습니다.

2024-06-29 12:51 UTC, KNU-K commented on src/getFirstHangulLetters.ts
> +export function getFirstHangulLetters(text: string) {
@okinawaa  수정 완료 했습니다.

2024-06-29 12:53 UTC, okinawaa requested changes
아래와 같은 lint오류 세가지가 발생하고 있어서, 해결부탁드립니다

<img width="627" alt="image" src="https://github.com/toss/es-hangul/assets/69495129/5c7a899d-fcf2-4eab-9c34-fb9da7320957">

2024-06-29 12:59 UTC, KNU-K reviewed
수정했습니다

2024-06-29 13:00 UTC, okinawaa requested changes
src/index.ts에 
패키지에서 사용할 수 있도록 export 하고, 문서화 작업도 진행해주실 수 있나요?

2024-06-29 13:02 UTC, KNU-K commented
@okinawaa 문서화는 어디서 진행하면될까요?

2024-06-29 13:03 UTC, okinawaa commented
다른 메서드들의
.ko.mdx
.en.mdx 참고하셔서 일관성있게 진행해주시면 좋을 것 같아요!

2024-06-29 13:15 UTC, okinawaa commented on src/_internal/hangul.ts
> +export function isHangulOnly(text: string): boolean {
https://github.com/toss/es-hangul/pull/136

이 PR이 머지되면, #136 에서 제공되는 메서드로 이것을 대체하는것은어떤가요?

2024-06-29 13:17 UTC, KNU-K commented on src/_internal/hangul.ts
> +export function isHangulOnly(text: string): boolean {
좋습니다.

2024-06-29 13:19 UTC, okinawaa commented on docs/src/pages/docs/api/getHangulAcronym.ko.mdx
> +(We don't deal with non-Korean sentences; we don't deal with additional Korean + English sentences.)
한글문서와 영어 문서가 반대로 되어있는것 같습니다!

2024-06-29 13:23 UTC, okinawaa commented on docs/src/pages/docs/api/getHangulAcronym.ko.mdx
> +문자열의 초성 일치 검색을 수행합니다.
이 부분 수정이 필요합니다

2024-06-29 13:24 UTC, okinawaa commented on src/getHangulAcronym.ts
> +  if (!isHangulOnly(text)) {
#136 PR이 머지되어서, 이 부분 재표현 가능할 것 같습니다

2024-06-29 13:33 UTC, okinawaa commented on docs/src/pages/docs/api/getHangulAcronym.en.mdx
> +  // 복수 명사로 이루워진 문자열 (e.g. '버스 충전', '치킨과 맥주')
```suggestion
  // 복수 명사로 이루어진 문자열 (e.g. '버스 충전', '치킨과 맥주')
```

2024-06-29 13:34 UTC, okinawaa commented on src/_internal/hangul.ts
> +export function isHangulOnly(text: string): boolean {
불필요해졌으니, 삭제해도 좋을 것 같아요

2024-06-29 13:34 UTC, okinawaa commented on src/getHangulAcronym.ts
> +  }
parseHangul을 사용하면 내부적으로 에러처리까지해줘서 더 좋을 것 같아요

2024-06-29 13:35 UTC, okinawaa commented on src/getHangulAcronym.ts
> +export function getHangulAcronym(text: string) {
파라미터를 조금 더 명확하게 해주면 좋겠습니다.
그래야, 한글만 이 함수에 넣어야한다는것을 조금이라도 더 알 것 같아요

```suggestion
export function getHangulAcronym(hangul: string) {
```

2024-06-29 13:36 UTC, okinawaa commented on src/getHangulAcronym.ts
> +  return firstHangulLetters;
한문장으로 작성해도 크게 가독성을 해치지 않을 것 같아요

```suggestion
return text.split(' ').map(word => word.charAt(0));
```

2024-06-29 13:49 UTC, okinawaa submitted a review, later dismissed
긴 작업 감사합니다 🚀

2024-06-29 13:52 UTC, okinawaa approved these changes

2024-06-29 13:52 UTC, merged

2024-06-29 13:53 UTC, KNU-K commented
@okinawaa 감사합니다.

2024-06-29 14:23 UTC, okinawaa commented on src/getFirstHangulLetters.ts
> +export function getFirstHangulLetters(text: string) {
@KNU-K 님 혹시, 이 함수명을 `acronymizeHangul` 로 수정할 수 있나요?
get이라는 워딩을 사용하기보다는, 동사형을 사용하면 더 직관적이라고 생각하기 때문입니다.
이미 1.3.8버전에 배포되었지만, 빠르게 수정하면 불편함을 덜어줄 수 있을 것 같아요.
혹시 작업이 힘드시다면, 제가 진행해도 됩니다!

2024-06-29 14:58 UTC, KNU-K commented on src/getFirstHangulLetters.ts
> +export function getFirstHangulLetters(text: string) {
@okinawaa 제가 진행하겠습니다!

2024-06-29 14:59 UTC, okinawaa commented on src/getFirstHangulLetters.ts
> +export function getFirstHangulLetters(text: string) {
앗 감사합니다..!! 연관된 파일 모두 챙겨주시면 감사하겠습니다~!

2024-06-29 15:03 UTC, KNU-K commented on src/getFirstHangulLetters.ts
> +export function getFirstHangulLetters(text: string) {
https://github.com/toss/es-hangul/issues/129 이부분 진행할까하는데, 혹시 진행하면서 PR에 포함시켜도 될까요??
@okinawaa

2024-06-29 15:04 UTC, okinawaa commented on src/getFirstHangulLetters.ts
> +export function getFirstHangulLetters(text: string) {
명확히 다른기능이라, 두 가지 다른 PR로 진행하였으면 해요

2024-06-29 15:05 UTC, KNU-K commented on src/getFirstHangulLetters.ts
> +export function getFirstHangulLetters(text: string) {
넵