chore: docs, changeset scripts 추가
toss/es-hangul pull request #220
Opened 2024-08-05 07:15 UTC by anonymousRecords

## Overview

더 편리하게 오픈소스에 기여할 수 있다고 생각해서, 
changeset, doc 관련하여 스크립트를 추가했습니다.

### 변경 전
```ts
  "scripts": {
    "attw": "attw --pack",
    "build": "tsup",
    "changeset:publish": "changeset publish",
    "changeset:version": "changeset version",
    "packlint": "packlint sort -R",
    "publint": "publint --strict",
    "test": "vitest run --coverage --typecheck",
    "test:watch": "vitest --ui --coverage --typecheck",
    "typecheck": "tsc --noEmit"
  },
```

### 변경 후
```ts
  "scripts": {
    ...
    "changeset": "changeset",
    "changeset:add": "changeset add",
    ...
    "docs:dev": "yarn workspace docs dev",
    "docs:build": "yarn workspace docs build",
    "docs:start": "yarn workspace docs start",
    "predocs:build": "yarn build"  
  },
```

## PR Checklist

- [x] I read and included theses actions below

1. I have read the [Contributing Guide](https://github.com/toss/es-hangul/blob/main/.github/CONTRIBUTING.md)
2. I have written documents and tests, if needed.

2024-08-09 05:38 UTC, okinawaa requested changes

2024-08-09 05:38 UTC, okinawaa commented on package.json
> +    "predocs:build": "yarn build"
요건 어떤 용도인가용? 
현재 yarn build하면 가장 위 스크립트인 tsup이 실행되도록 되어있어서요!

2024-08-09 05:38 UTC, okinawaa commented on .changeset/swift-toys-appear.md
https://github.com/toss/es-hangul/blob/main/.changeset/config.json#L9

더 이상 docs는 changeset으로 관리되고 있지 않아서 제거되어도 될 것 같아요!!

2024-08-13 04:11 UTC, anonymousRecords commented
@okinawaa 

피드백 확인하고 아래와 같이 수정했습니다.

1. 불필요한 중복을 야기할 수 있어서 `"predocs:build": "yarn build"` 제거
2. changeset 관련 스크립트 제거

---

>요건 어떤 용도인가용? 현재 yarn build하면 가장 위 스크립트인 tsup이 실행되도록 되어있어서요!

언급해 주신 부분은 제가 중복 야기하는지 확인을 못 했었어서 제거했습니당

2024-08-13 04:15 UTC, anonymousRecords commented on .changeset/swift-toys-appear.md
반영했습니당!

2024-08-13 04:15 UTC, anonymousRecords commented on package.json
> +    "predocs:build": "yarn build"
`"build": "tsup"`이랑 중복되는 거 같아서, 제거했습니당

2024-08-16 06:34 UTC, okinawaa approved these changes
늦게 확인하여 죄송합니다!
정말 감사합니다~!

2024-08-16 06:34 UTC, merged